CREATE DATABASE `pharaohs_palace`
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE `pharaohs_palace`;

CREATE TABLE `t_funcionario` (
  `COD_FUNC` tinyint(4) NOT NULL AUTO_INCREMENT,
  `NOME`     varchar(50) DEFAULT NULL,
  `LOGIN`    varchar(30) DEFAULT NULL,
  `SENHA`    varchar(15) DEFAULT NULL,
  PRIMARY KEY (`COD_FUNC`)
) DEFAULT CHARSET = utf8;

CREATE TABLE `t_tipo_hospede` (
  `COD_TIP_HOSP` tinyint(4) NOT NULL AUTO_INCREMENT,
  `HOSP_DESC`    varchar(30) DEFAULT NULL,
  `SEXO`         char(1) DEFAULT NULL,
  PRIMARY KEY (`COD_TIP_HOSP`)
) DEFAULT CHARSET = utf8;

CREATE TABLE `t_hospede` (
  `COD_HOSPEDE`  int(11) NOT NULL AUTO_INCREMENT,
  `TIPO_HOSPEDE` tinyint(4) DEFAULT NULL,
  `NOME`         varchar(50) DEFAULT NULL,
  `TELEFONE`     bigint(20) DEFAULT NULL,
  PRIMARY KEY (`COD_HOSPEDE`),
  KEY `FK_TIP_HOSP_HOSPEDE` (`TIPO_HOSPEDE`),
  CONSTRAINT `FK_TIP_HOSP_HOSPEDE` FOREIGN KEY (`TIPO_HOSPEDE`) REFERENCES `t_tipo_hospede` (`COD_TIP_HOSP`)
) DEFAULT CHARSET = utf8;

CREATE TABLE `t_reserva` (
  `COD_RESERVA` int(11) NOT NULL AUTO_INCREMENT,
  `COD_FUNC`    tinyint(4) DEFAULT NULL,
  `COD_HOSP`    int(11) DEFAULT NULL,
  `STATUS`      tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`COD_RESERVA`),
  KEY `FK_FUNC_RESERVA` (`COD_FUNC`),
  KEY `FK_HOSP_RESERVA` (`COD_HOSP`),
  CONSTRAINT `FK_FUNC_RESERVA` FOREIGN KEY (`COD_FUNC`) REFERENCES `t_funcionario` (`COD_FUNC`),
  CONSTRAINT `FK_HOSP_RESERVA` FOREIGN KEY (`COD_HOSP`) REFERENCES `t_hospede` (`COD_HOSPEDE`)
) DEFAULT CHARSET = utf8;

CREATE TABLE `t_tipo_quarto` (
  `COD_TIP_QUARTO` tinyint(4) NOT NULL AUTO_INCREMENT,
  `QTD_PESSOAS`    tinyint(4) DEFAULT NULL,
  `FRIGOBAR`       char(1) DEFAULT NULL,
  `BANHEIRO`       char(1) DEFAULT NULL,
  PRIMARY KEY (`COD_TIP_QUARTO`)
) DEFAULT CHARSET = utf8;

CREATE TABLE `t_quarto` (
  `NUM_QUARTO`     int(11) NOT NULL AUTO_INCREMENT,
  `COD_TIP_QUARTO` tinyint(4) DEFAULT NULL,
  `VALOR_QUARTO`   decimal(5,2) DEFAULT NULL,
  PRIMARY KEY (`NUM_QUARTO`),
  KEY `FK_TIP_QUART_QUARTO` (`COD_TIP_QUARTO`),
  CONSTRAINT `FK_TIP_QUART_QUARTO` FOREIGN KEY (`COD_TIP_QUARTO`) REFERENCES `t_tipo_quarto` (`COD_TIP_QUARTO`)
) DEFAULT CHARSET = utf8;

CREATE TABLE `t_hospedagem` (
  `COD_HOSPEDAGEM` int(11) DEFAULT NULL,
  `NUM_QUARTO`     int(11) DEFAULT NULL,
  `COD_RESERVA`    int(11) DEFAULT NULL,
  `STATUS`         tinyint(4) DEFAULT NULL,
  `DATA_ENTRADA`   datetime DEFAULT NULL,
  `DATA_SAIDA`     datetime DEFAULT NULL,
  `VALOR_TOTAL`    decimal(7,2) DEFAULT NULL,
  KEY `FK_RESERVA_QUARTO` (`NUM_QUARTO`),
  KEY `FK_QUARTO_RESERVA` (`COD_RESERVA`),
  CONSTRAINT `FK_QUARTO_RESERVA` FOREIGN KEY (`COD_RESERVA`) REFERENCES `t_reserva` (`COD_RESERVA`),
  CONSTRAINT `FK_RESERVA_QUARTO` FOREIGN KEY (`NUM_QUARTO`) REFERENCES `t_quarto` (`NUM_QUARTO`)
) DEFAULT CHARSET = utf8;